name: .NET and Docker Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0" # You can specify your desired .NET SDK version here

      - name: Restore dependencies
        working-directory: ./CCM
        run: dotnet restore

      - name: Build
        working-directory: ./CCM
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        working-directory: ./CCM
        run: dotnet publish --configuration Release --no-restore --output ./publish

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: CCM
          file: CCM/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ccm-apis:latest
